### ISSUE TITLE
Add session refreshing

### ISSUE THREAD

**Issue by ThatTonybo** [nodecord/nodecord#1]
This will be the first "bug" listed for `nodecord` in 2019.

Currently, bots running on the library cannot last more than about a couple hours due to sessions dying and being unable to reconnect or refresh. This is a major downfall, and a feature that needs to be added.

As a side note to this, **`nodecord` is not dead. It's just on hiatus while we're all busy.**

**Comment by IceeMC** [comment]
yes

**Comment by ThatTonybo** [comment]
This will be started soon.

**Comment by ThatTonybo** [comment]
This will be fixed in v2.
