### ISSUE TITLE
make it work on user accounts

### ISSUE THREAD

**Issue by 9xN** [nodecord/nodecord#8]
title

**Comment by ThatTonybo** [comment]
1. This is, for the most part, a dead project
2. Discord does not support user account botting, it's against the ToS

**Comment by 9xN** [comment]
did i stutter?

**Comment by ThatTonybo** [comment]
Re-read my answer

**Comment by 9xN** [comment]
> Re-read my answer

pls add user support literally nothing will happen

**Comment by ThatTonybo** [comment]
Have you even read my message? It's very clear: This project is dead. We don't maintain it anymore, it doesn't function due to API changes.

**Comment by 9xN** [comment]
> Have you even read my message? It's very clear: This project is dead. We don't maintain it anymore, it doesn't function due to API changes.

well thats kinda stinky
